fixed polygon issues
1. Fixed following error:

shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7f120c115dc0>

    - issue is with predicted polygons, not with ground truth (but still add check to ground truth?)
    - 64% of predicted polygons were valid.
    - fix involved removing predicted polygons that were not valid (under writeMaskToDisk) = {'geometry':[i for i in res if i.type == 'Polygon' and i.is_valid]}
    - number of invalid features drastically decreased when epochs went from 2 to 10, so this is an issue of not training enough

2. Built more robust line generation routine

    - instead of making default same length lines to divide all the shadow polygons (these could be too short), it now has a exact_mode that makes them only exactly as long as they need to be, and no shorter than needed using trig :)

Random Notes
    - any coordinates expressed in EPSG 32628 are already in metric units.