SUMMARY: Pipeline is working end to end! -------
Tons of changes detailed below @JesseRMeyer

NOTES
-----

One choice I'm proud of making was not using the following quick fix:

annotations_gdf['geometry'] = annotations_gdf.buffer(0)

I was having weird issues with the annotations geodataframe not being able to save because of the following error:

shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7fe86878a6d0>

At first I used that .buffer(0) fix because it was the quickest/easiest to implement, but I thought better about it and then implemented a more robust fix after taking a second look at things:

annotations_gdf['geometry'] = [make_valid(i) for i in annotations_gdf['geometry']]

I'm glad I did this, because just doing a .buffer(0) seems really suspicious and would likely lead to unkown consequences.

DONE
----
[x] full pipeline (get predicted heights out)
[x] make sure train and val are reporting all stats to csv file (tversky loss, dice_loss, spec, sens, acc)
[x] add plot for the above! (run example for 10 epochs)
[x] get test to report if annotations exist
[x] plot two hist, save
[x] fix cutlines file shortcut
[x] FIXED: having issues with geopandas (new version dumps a ton of gobbly gook instead of simple EPSG:number for crs)
[x] delete unesssary funcs in utils,
[x] fixed output dirs in pipeline...
[x] FIX: shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7fe86878a6d0>
[x] FIX: fiona.errors.DriverError: Failed to create directory temp/tensorflow/temp/tensorflow/predictions/heights_analysis_output_0.gpkg for shapefile datastore.

TO DO
-----
[ ] merge into dev, keep pytorch in pytorch branch but burn it out of dev?